name: Create branch Workflow

on:
  workflow_dispatch:

jobs:
  update-patches:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Git identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        touch "hello"
    - name: Create release branch
      run: |
        git checkout -b releases/test
        git add . && git commit -m "Create release test"
        git push -u origin releases/test
