name: E2E

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  runs-on: "${{ matrix.flavor }}"
  echo_hello:
    name: Echo Hello
    strategy:
      fail-fast: false
      matrix:
        flavor:
          - [hello, world]
    steps:
      - name: apt-get
        if: always()
      - name: Print env
        run: env
      - name: Print event
        run: cat "$GITHUB_EVENT_PATH"
