name: E2E

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  echo_hello:
    name: Echo Hello
    runs-on: self-hosted 
    steps:
      - name: Print Hello
        run: echo "Hello!"
      - name: Print env
        run: env

