name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    permissions:
      id-token: write # Enable OIDC
      pull-requests: write
      contents: write
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Set up Git identity
      run: |
        git config --global user.name "YangSoo Yoon"
        git config --global user.email "yangsoo.yoon@canonical.com"
    - name: Get commits
      id: get-commits
      run: |
        # Get latest commit
        LATEST_COMMIT=$(git rev-parse HEAD)
        echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_OUTPUT
        echo "LATEST_COMMIT_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
        # Get previous processed commit
        if [ -f ../patches/last_processed_commit.txt ]; then
          PREVIOUS_COMMIT=$(cat ../patches/last_processed_commit.txt)
          PREVIOUS_COMMIT_SHORT="${PREVIOUS_COMMIT:0:7}"
          echo "PREVIOUS_COMMIT=$PREVIOUS_COMMIT" >> $GITHUB_OUTPUT
          echo "PREVIOUS_COMMIT_SHORT=$PREVIOUS_COMMIT_SHORT" >> $GITHUB_OUTPUT
        else
          echo "PREVIOUS_COMMIT=" >> $GITHUB_OUTPUT
          echo "PREVIOUS_COMMIT_SHORT=" >> $GITHUB_OUTPUT
        fi

    - name: Create dummy commit for PR
      run: |
        < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c10 | xargs -0 touch


    - name: Import and configure the GPG key for Noctua
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSKEY }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Create a PR for local changes
      uses: canonical/create-pull-request@main
      with:
        token: ${{ secrets.PAT }}
        commit-message: "chore: update charm libraries"
        committer: YangSoo Yoon <yangsoo.yoon@canonical.com>
        author: YangSoo Yoon <yangsoo.yoon@canonical.com>
        title: "chore: update charm libraries"
        body: |
          Automated action to fetch the latest minor and major versions of all charm libraries used by this charm. The branch of this PR 
          will be overwritten during the next check. Unless you really know what you're doing, you 
          most likely don't want to push any commits to this branch.

          The PR will be auto-merged if the CI is green, on the next iteration of the workflow.
        branch: "test"
        delete-branch: true
