name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        type: string
        description: 'echo message'
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo '${{ inputs.message }}'
