name: Test Workflow

on:
  push:


jobs:
  test:
    runs-on: [self-hosted]

    steps:
    - name: echo arch
      run: dpkg --pring-architecture
    - uses: actions/checkout@v5
    - uses: actions/checkout@v4
    - uses: actions/checkout@v3
