name: Test Workflow

on:
  workflow_call:
    inputs:
        message:
          required: true
          type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo '${{ inputs.message }}'
